module.exports = {
    BUTTON_A: 0,
    BUTTON_B: 1,
    BUTTON_X: 2,
    BUTTON_Y: 3,
    BUTTON_L: 4,
    BUTTON_R: 5,
    LEFT_STICK: 6,
    RIGHT_STICK: 7,
    START: 8,
    OPTIONS: 9,
    HOME: 10,
    MEDIA: 11,
    DIR_UP: 12,
    DIR_DOWN: 13,
    DIR_LEFT: 14,
    DIR_RIGHT: 15,
    LEFT_AXIS_X: 16,
    LEFT_AXIS_Y: 17,
    RIGHT_AXIS_X: 18,
    RIGHT_AXIS_Y: 19,
    LEFT_TRIGGER: 20,
    RIGHT_TRIGGER: 21
};