const Controls = require('./Controls');
const Keys = require('./KeyboardKeys');

module.exports = {
    ENABLE_KEYBOARD: false,
    ENABLE_GAMEPAD: false,
    GP_BUTTON_A: Controls.BUTTON_A,
    GP_BUTTON_B: Controls.BUTTON_B,
    GP_BUTTON_X: Controls.BUTTON_X,
    GP_BUTTON_Y: Controls.BUTTON_Y,
    GP_BUTTON_L: Controls.BUTTON_L,
    GP_BUTTON_R: Controls.BUTTON_R,
    GP_BUTTON_OPTIONS: Controls.BUTTON_OPTIONS,
    GP_BUTTON_START: Controls.BUTTON_START,
    GP_LEFT_STICK: Controls.LEFT_STICK,
    GP_RIGHT_STICK: Controls.RIGHT_STICK,
    GP_LEFT_AXIS_X: 0,
    GP_LEFT_AXIS_Y: 1,
    GP_RIGHT_AXIS_X: 2,
    GP_RIGHT_AXIS_Y: 3,
    GP_DIRECTION_PAD_X: 12,
    GP_DIRECTION_PAD_Y: 13,
    GP_LEFT_TRIGGER: Controls.LEFT_TRIGGER,
    GP_RIGHT_TRIGGER: Controls.RIGHT_TRIGGER,
    KB_BUTTON_A: Keys.B,
    KB_BUTTON_B: Keys.H,
    KB_BUTTON_X: Keys.G,
    KB_BUTTON_Y: Keys.Y,
    KB_BUTTON_L: Keys.T,
    KB_BUTTON_R: Keys.U,
    KB_BUTTON_OPTIONS: Keys.SHIFT,
    KB_BUTTON_START: Keys.ENTER,
    KB_LEFT_STICK: Keys.O,
    KB_RIGHT_STICK: Keys.P,
    KB_LEFT_AXIS_X_POS: Keys.D,
    KB_LEFT_AXIS_X_NEG: Keys.A,
    KB_LEFT_AXIS_Y_POS: Keys.W,
    KB_LEFT_AXIS_Y_NEG: Keys.S,
    KB_RIGHT_AXIS_X_POS: Keys.LEFT,
    KB_RIGHT_AXIS_X_NEG: Keys.RIGHT,
    KB_RIGHT_AXIS_Y_POS: Keys.UP,
    KB_RIGHT_AXIS_Y_NEG: Keys.DOWN,
    KB_DIRECTION_PAD_X_POS: Keys.L,
    KB_DIRECTION_PAD_X_NEG: Keys.J,
    KB_DIRECTION_PAD_Y_POS: Keys.I,
    KB_DIRECTION_PAD_Y_NEG: Keys.K,
    KB_LEFT_TRIGGER: null,
    KB_RIGHT_TRIGGER: null
};
