const Controls = require('./Controls');
const Keys = require('./Keys');

module.exports = {
    ENABLE_KEYBOARD: false,
    ENABLE_GAMEPAD: true,
    GP_BUTTON_A: Controls.BUTTON_A,
    GP_BUTTON_B: Controls.BUTTON_B,
    GP_BUTTON_X: Controls.BUTTON_X,
    GP_BUTTON_Y: Controls.BUTTON_Y,
    GP_BUTTON_L: Controls.BUTTON_L,
    GP_BUTTON_R: Controls.BUTTON_R,
    GP_OPTIONS: Controls.OPTIONS,
    GP_START: Controls.START,
    GP_HOME: Controls.HOME,
    GP_LEFT_STICK: Controls.LEFT_STICK,
    GP_RIGHT_STICK: Controls.RIGHT_STICK,
    GP_DIR_UP: Controls.DIR_UP,
    GP_DIR_DOWN: Controls.DIR_DOWN,
    GP_DIR_LEFT: Controls.DIR_LEFT,
    GP_DIR_RIGHT: Controls.DIR_RIGHT,
    GP_AXIS_DEAD_ZONE: 0.25,
    GP_LEFT_AXIS_X: 0,
    GP_LEFT_AXIS_Y: 1,
    GP_RIGHT_AXIS_X: 3,
    GP_RIGHT_AXIS_Y: 4,
    GP_LEFT_TRIGGER: 2,
    GP_RIGHT_TRIGGER: 5,
    KB_BUTTON_A: Keys.B,
    KB_BUTTON_B: Keys.H,
    KB_BUTTON_X: Keys.G,
    KB_BUTTON_Y: Keys.Y,
    KB_BUTTON_L: Keys.Q,
    KB_BUTTON_R: Keys.E,
    KB_OPTIONS: Keys.SHIFT,
    KB_START: Keys.ENTER,
    KB_HOME: Keys.SPACE,
    KB_LEFT_STICK: Keys.O,
    KB_RIGHT_STICK: Keys.P,
    KB_LEFT_AXIS_X_POS: Keys.D,
    KB_LEFT_AXIS_X_NEG: Keys.A,
    KB_LEFT_AXIS_Y_POS: Keys.W,
    KB_LEFT_AXIS_Y_NEG: Keys.S,
    KB_RIGHT_AXIS_X_POS: Keys.LEFT,
    KB_RIGHT_AXIS_X_NEG: Keys.RIGHT,
    KB_RIGHT_AXIS_Y_POS: Keys.UP,
    KB_RIGHT_AXIS_Y_NEG: Keys.DOWN,
    KB_DIR_RIGHT_POS: Keys.L,
    KB_DIR_LEFT: Keys.J,
    KB_DIR_UP: Keys.I,
    KB_DIR_DOWN: Keys.K,
    KB_LEFT_TRIGGER: null,
    KB_RIGHT_TRIGGER: null
};
